name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the hello-world Docker image
      run: |
        echo $CR_PAT | docker login ghcr.io -u jonashackt --password-stdin
        docker build . --tag hello-world
        docker run hello-world
      env:
        CR_PAT: ${{ secrets.CR_PAT }}

